
export ML4FPGA_TOP_DIR=/gluonfs1/home/hdtrdops/soft_ml4fpga

# Start conda environment
source $ML4FPGA_TOP_DIR/miniconda/etc/profile.d/conda.sh
conda activate ml4fpga

# The path where edpm stores its JSon database and creates env files
export EDPM_DATA_PATH=$ML4FPGA_TOP_DIR/edpm_data

# This tells EDPM not to generate source thisroot.sh
export ROOT_INSTALLED_BY_CONDA=1

# source environment generated by EDPM
# means ROOT and others
source $EDPM_DATA_PATH/env.sh

# =============================
# jana4ml4fpga
# =============================
export JANA_PLUGIN_PATH=$ML4FPGA_TOP_DIR/jana4ml4fpga/jana4ml4fpga-main/install/plugins${JANA_PLUGIN_PATH:+:${JANA_PLUGIN_PATH}}
export PATH=$ML4FPGA_TOP_DIR/jana4ml4fpga/jana4ml4fpga-main/install/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=$ML4FPGA_TOP_DIR/jana4ml4fpga/jana4ml4fpga-main/install/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}